name: ci-base

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
      -
        name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3.3.0
        with:
          context: .
          file: Dockerfile-base
          push: true
          tags: dennischancs/web3-workspace-images:ubuntu-22.04
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: dennischancs/web3-workspace-images